import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.css"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Navbar } from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import UserProvider from './../UserProvider';
import CountProvider from "@/CountProvider";


const Josefin_SansFont = Josefin_Sans({
  subsets: ["latin"],
  weight:['100','400', '700']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Josefin_SansFont.className}`}
        
      >

        <CountProvider>
        <UserProvider>
          <Navbar/>
        <main className=" p-5">
          {children}
        </main>
        <Toaster/>


        <Footer/>
        </UserProvider>
        </CountProvider>
      </body>
    </html>
  );
}
