import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.css"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Navbar } from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import UserProvider from './../UserProvider';
import CountProvider from "@/CountProvider";


const Josefin_SansFont = Josefin_Sans({
  subsets: ["latin"],
  weight:['100','400', '700']
})


export const metadata: Metadata = {
  title: "Exclusive",
  description: "Generated by Amr Mazied Badawi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${Josefin_SansFont.className} `}
        
      >

        <CountProvider>
        <UserProvider>
            <Navbar />
            <div className="flex flex-col min-h-screen">
              <main className="flex-grow dark:bg-gray-900 p-5">
                {children}
              </main>
              <Toaster/>
              <footer className="bg-blue-50 pt-8 pb-6 dark:bg-gray-800">
                  <div className="container mx-auto px-4">
                    <Footer/>
                  </div>
               </footer>
            </div>

          
        </UserProvider>
        </CountProvider>
      </body>
    </html>
  );
}
